### ISSUE TITLE
[feature request] read from multiple configs

### ISSUE THREAD

**Issue by sikoji** [insaneadinesia/go-mockemok#3]

**Comment by insaneadinesia** [comment]
Hello @sikoji , thanks for your feature request, read from multiple config files is a good feature since maybe you have much services to mocks, and it will be too long yaml mocking rules if you just have one config file.

For that, i already make an update to this project, please look changes in [this commit](https://github.com/insaneadinesia/go-mockemok/commit/c61c1e6aa2f44e9cce46d0e280225b0a00c965e0).

**Caution**
This feature will be breaking changes the old one
